steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/VerMunoz/demo-appweb"]
    env: ["PROJECT_ROOT=github.com/VerMunoz/demo-appweb"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/cool-bay-257604/demo-appweb:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/cool-bay-257604/demo-appweb:$REVISION_ID"
